name: CI

on:

  push:
 
  pull_request:
    branches: [ main ]
 
jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Install gtest manually
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && ls -la && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
        
      - name: Install vilgrind
        run: sudo apt update && sudo apt install valgrind
        
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
        
      - name: configure
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
        
      - name: make
        run: cd build && make
        
      - name: Run vilgrind
        run: cd build && valgrind --leak-check=full --error-exitcode=0 ./test_db

      - name: Run Test
        run: ./build/test_db
